config/routes.rb
RubyGarage::Application.routes.draw do
  root to: 'welcome#index'

  devise_for :users


  scope module: 'authenticated' do
    resources :projects, only: [ :index, :create, :update, :destroy ]
    resources :tasks, only: [ :create, :update ] do
      put :destroy,    :on => :collection
      put :complete,   :on => :member
      put :prioritize, :on => :member
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  # Associations
  belongs_to :user
  has_many   :tasks

  # Validations
  validates :name, presence: true

  with_options if: -> { name.present? } do
    # We don't want extra errors
    validates :name, uniqueness: true
  end

  scope :recent_first, -> { order('projects.created_at DESC') }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  acts_as_list scope: :project

  validates :name, presence: true
  with_options if: -> { name.present? } do
    validates :name, uniqueness: { :scope => :project_id }
  end

  default_scope        -> { order('tasks.position DESC') }
  scope :recent_first, -> { order('tasks.created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable


  has_many :projects
  has_many :tasks, :through => :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authenticated/base_controller.rb
class Authenticated::BaseController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/authenticated/projects_controller.rb
class Authenticated::ProjectsController < Authenticated::BaseController
  before_filter :find_project!, only: [ :update, :destroy ]

  def index
    @projects = current_user.projects.page(params[:page]).recent_first
    @project  = Project.new
  end

  def create
    @project = current_user.projects.create(project_params)

    if @project.persisted?
      render json: { entry: render_to_string(partial: 'project', locals: { project: @project }), message: I18n.t('flash.authenticated.projects.create.notice') },
             status: 202
    else
      render json: { errors: @project.errors }, status: 422
    end
  end

  def update
    if @project.update(project_params)
      render json: @project
    else
      render text: @project.errors.full_messages.join("<br />")
    end
  end

  def destroy
    @project.destroy

    render json: { message: I18n.t('flash.authenticated.projects.destroy.notice') }, status: 200
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end

  def find_project!
    @project = current_user.projects.find(params[:id])
  end
end

app/controllers/authenticated/tasks_controller.rb
class Authenticated::TasksController < Authenticated::BaseController
  before_filter :find_task!,    only: [ :update, :prioritize, :complete ]
  before_filter :find_project!, only: [ :create ]

  def create
    @task = @project.tasks.create(task_params)

    if @task.persisted?
      render json: { entry: render_to_string(partial: 'task', locals: { task: @task }), message: I18n.t('flash.authenticated.tasks.create.notice') },
             status: 202
    else
      render json: { errors: @task.errors }, status: 422
    end
  end

  # Expects an array of ids
  def destroy
    current_user.tasks.where(id: params[:task][:task_ids]).
      destroy_all

    render nothing: true, status: 200
  end

  def complete
    @task.update(completed: !@task.completed)

    render nothing: true, status: 200
  end

  def update
    if @task.update(task_params)
      render json: @task, status: 202
    else
      render text: @task.errors.full_messages.join("<br />")
    end
  end

  def prioritize
    @task.insert_at(params[:position])

    render nothing: true, status: 200
  end

  private

  def task_params
    params.require(:task).permit(:name, :position)
  end

  def find_task!
    @task = current_user.tasks.find(params[:id])
  end

  def find_project!
    @project = current_user.projects.find(params[:task][:project_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for model
    return "" if model.errors.empty?

    messages = model.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div class="alert alert-error" id="error-explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def icon_label(classes, text = '')
    "<i class='#{ classes }'></i> #{ text }".html_safe
  end


  def page_header(text = nil, subtext = nil)
    "<div class='page-header'> <h3> #{ text ? text : t('.header') } #{ subtext ? ('<small>' + subtext + '</small>') : ''} </h3> </div>".html_safe
  end

  def no_results(text = nil)
    "<div class='no-results well'> <h3> #{ text ? text : t('.no_results') } </h3> </div>".html_safe
  end

  def subheader(text)
    "<div class='page-header'> <h3> <small> #{ text } </small> </h3> </div>".html_safe
  end

  def heads_up! text
    "<div class='heads-up'> <strong> #{ t('common.heads_up!') } </strong> #{ text } </div>".html_safe
  end

  def inline_heads_up! text
    "<span class='inline-heads-up'> <span class='label label-info'> #{ t('common.heads_up!') } </span> <strong> #{ text } </span>".html_safe
  end
end

app/helpers/authenticated/projects_helper.rb
module Authenticated::ProjectsHelper
end

app/helpers/authenticated/tasks_helper.rb
module Authenticated::TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_footer.erb
 <div id="footer">
  <div class="container">
    <div class="message"> <%= t '.message' %> </div>
  </div>
</div>

app/views/application/_header.erb
<div class="navbar navbar-inverse" id='header'>

  <div class="navbar-inner">
    <%= link_to t('.brand'), root_path, class: 'brand' %>

    <ul class="nav">
    </ul>

    <ul class='nav pull-right'>
      <%- if user_signed_in? %>
        <li><%= link_to t('.application'),  projects_path %></li>
        <li><%= link_to t('auth.sign_out'), destroy_user_session_path, method: 'delete' %></li>
      <% else %>
        <li><%= link_to t('auth.sign_in'), new_user_session_path %></li>
        <li><%= link_to t('auth.sign_up'), new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>

</div>

app/views/application/_notifications.erb
<div class='container'>

  <div id='notifications' class='span3'>
    <%- if flash[:notice].present? %>
      <div class='alert alert-info'>
        <button type="button" class="close" data-dismiss="alert"> <%= t 'common.x' %> </button>
        <h4> <%= t 'common.heads_up!' %> </h4>

        <%= flash[:notice] %>
      </div>
    <% end %>

    <%- if flash[:alert].present? %>
      <div class='alert alert-error'>
        <button type="button" class="close" data-dismiss="alert"> <%= t 'common.x' %> </button>
        <h4> <%= t 'common.warning!' %> </h4>

        <%= flash[:alert] %>
      </div>
    <% end %>


    <div id='alert-template' class='hidden alert notification'>
    </div>
  </div>


</div>

app/views/authenticated/projects/_project.erb
<div class='project' id='project-<%= project.id %>'>
  <div class='project-header'>
    <span class='calendar'> <%= icon_label 'icon-calendar' %> </span>
    <span class='project-name' id='project-<%= project.id %>' data-resource='project' data-name='name' data-url='<%= project_path(project) %>'>
      <%= project.name %>
    </span>

    <div class='pull-right project-options'>
      <span class='edit-project'>
        <%= link_to '#', id: "edit-project-name-#{project.id}", class: 'edit-project-name' do %>
          <%= icon_label 'icon-pencil' %>
        <% end %>
      </span>
      <span class='destroy-project'>
        <%= link_to project, remote: true, method: 'delete', class: 'destroy-project', title: t('.destroy'), data: { confirm: t('common.are_you_sure?') } do %>
          <%= icon_label 'icon-trash' %>
        <% end %>
      </span>
    </div>
  </div>

  <div class='project-body'>
    <div class='new-task-container'>
      <%= icon_label 'icon-plus new-task-label' %>

      <%= simple_form_for Task.new, remote: true, html: { id: "new-project-task-#{project.id}", class: 'new-task form-inline' } do |form| %>
        <%= form.input :name, required: true, label: false, placeholder: t('authenticated.tasks.new.input_placeholder'), input_html: { class: 'span5' } %>
        <%= form.input :project_id, type: :hidden, input_html: { value: project.id } %>
        <%= form.submit t('common.submit'), class: 'btn btn-success', disabled: true, data: { disable_with: t('common.please_wait') } %>
      <% end %>
    </div>

    <div class='project-tasks'>
      <section class='todo'>
        <%= simple_form_for Task.new, method: 'put', remote: true, html: { class: 'bulk-destroy-tasks' } do |form| %>
          <ul class="todo-controls">
            <li> <%= link_to nil, class: 'delete-selected-tasks', title: 'Delete selected tasks' do %> <%= icon_label 'icon-trash' %> <% end %> </li>
          </ul>

          <ul class='todo-list'>
            <%= render partial: 'authenticated/tasks/task', collection: project.tasks, locals: { form: form } %>
          </ul>
        <% end %>
      </section>
    </div>
  </div>
</div>

app/views/authenticated/projects/index.html.erb
<%= page_header %>

<div id='projects'>
  <%= render @projects %>
</div>

<div class='center'>
  <%= link_to nil, id: 'new-project-toggler', class: 'btn btn-danger' do %>
    <%= icon_label 'icon-plus', t('.new') %>
  <% end %>
</div>


<div id='new-project' class='well span6'>
  <%= simple_form_for @project, remote: true, html: { id: 'new-project', class: 'form-horizontal' } do |form| %>
    <%= form.input :name, required: true %>

    <%= form.submit t('common.submit'), class: 'btn btn-success', disabled: true, data: { disable_with: t('common.please_wait') } %>
  <% end %>
</div>

app/views/authenticated/tasks/_task.erb
<li class='task-item <%= "completed" if task.completed %>' id='task-item-<%= task.id%>'>
  <input type='checkbox' id='task-<%= task.id %>' name='task[task_ids][]' value='<%= task.id %>'/>
  <label class="toggle" for='task-<%= task.id %>'></label>
  <span class='task-name' id='task-<%= task.id %>' data-resource='task' data-name='name' data-url='<%= task_path(task) %>'>
    <%= task.name %>
  </span>

  <div class='pull-right task-options'>
    <%= link_to complete_task_path(task), remote: true, method: 'put', class: 'complete-task', title: task.completed?? t('.uncomplete') : t('.complete') do %>
      <%= icon_label task.completed?? 'icon-thumbs-down' : 'icon-thumbs-up' %>
    <% end %>
    <%= link_to '#', id: "edit-task-name-#{task.id}", class: 'edit-task-name', title: t('.edit') do %>
      <%= icon_label 'icon-pencil' %>
    <% end %>
    <%= icon_label 'icon-resize-vertical task-drag-handle' %>
  </div>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyGarage</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= csrf_meta_tags %>
</head>

<%# the body attributes are used for JS init, styles encapsulation %>
<body id='<%= controller_path.dasherize.gsub('/', '-') %>' data-action='<%= action_name.dasherize %>' >
  <div id='wrapper'>
    <%= render 'header' %>
    <%= render 'notifications' %>

    <div id='main-content' class='container'>
      <%= yield %>

      <div id='push'></div>
    </div>
  </div>

  <%= render 'footer' %>
  <%= javascript_include_tag "application" %>
</body>


</html>

app/views/welcome/index.html.erb
<%= page_header %>

<%- if user_signed_in? %>
  <div class='well' id='project-news-section'>
    <%# Yes it has news :) %>

    <%= t('.news', url: projects_path).html_safe %>
  </div>
<% else %>
  <div id='authentication-options'>
    Please either <%= link_to t('auth.sign_in'), new_user_session_path, class: 'important' %> or 
    <%= link_to t('auth.sign_up'), new_user_registration_path, class: 'important' %> to see the project news (yes it has news)
  </div>
<% end %>